import React, { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { recoveryService } from '../../services/recovery';
import { AIDecisionCard } from '../../components/ai/AIDecisionCard';
import { Skeleton } from '../../components/ui/Skeleton';
import { EmptyState } from '../../components/ui/EmptyState';
import { Tabs } from '../../components/ui/Tabs';
import { Brain, Sparkles, ShieldCheck, Filter } from 'lucide-react';
import { RecoveryCase } from '../../types';

export const AIDecisionsPage = () => {
  const [filter, setFilter] = useState('All');
  
  const { data, isLoading, isError, refetch } = useQuery({ 
    queryKey: ['recoveryCases', 'ai_decisions'], 
    queryFn: () => recoveryService.getCases({ limit: 100 })
  });

  const rawItems: RecoveryCase[] = (data && typeof data === 'object' && 'items' in data && Array.isArray((data as { items: RecoveryCase[] }).items))
    ? (data as { items: RecoveryCase[] }).items
    : (Array.isArray(data) ? data : []);

  const filteredItems = rawItems.filter((item: RecoveryCase) => {
    const isBlocked = (item.status === 'stopped' || item.status === 'failed' || (item as unknown as { policy_result?: { allowed?: boolean } }).policy_result?.allowed === false);
    if (filter === 'All') return true;
    if (filter === 'Allowed') return !isBlocked;
    if (filter === 'Blocked') return isBlocked;
    return true;
  });

  const tabItems = [
    { id: 'All', label: 'All Decisions' },
    { id: 'Allowed', label: 'Allowed / Active' },
    { id: 'Blocked', label: 'Blocked / Stopped' }
  ];

  return (
    <div className="space-y-8 pb-12 selection:bg-green-500/30">
      
      {/* Top Banner Header */}
      <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4 bg-[#0c0c0e] border border-neutral-800 p-7 rounded-3xl relative overflow-hidden shadow-[0_10px_30px_rgba(0,0,0,0.8)]">
        <div className="absolute top-0 right-0 w-64 h-64 bg-green-500/5 rounded-full blur-3xl pointer-events-none" />
        
        <div className="relative z-10">
          <div className="flex items-center gap-2 mb-2">
            <div className="p-2 rounded-xl bg-green-500/10 border border-green-500/20 text-green-400">
              <Brain className="w-5 h-5 animate-pulse" />
            </div>
            <span className="text-xs font-mono uppercase tracking-widest text-green-400 font-bold">Autonomous Intelligence</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight font-mono">AI Decisions Engine</h1>
          <p className="text-neutral-400 text-xs sm:text-sm mt-1 max-w-xl font-mono leading-relaxed">
            Inspect real-time automated recovery decisions, risk confidence scoring, and neural diagnosis logs generated by the AI engine.
          </p>
        </div>

        <div className="flex items-center gap-3 relative z-10">
          <div className="px-4 py-2.5 rounded-2xl bg-neutral-900 border border-neutral-800 flex items-center gap-2.5 shadow-inner">
            <ShieldCheck className="w-4 h-4 text-green-400" />
            <span className="text-xs font-mono text-neutral-300">Engine Status: <strong className="text-green-400">ONLINE</strong></span>
          </div>
        </div>
      </div>

      {/* Tabs Filter Bar */}
      <div className="flex items-center justify-between gap-4 flex-wrap">
        <div className="w-full sm:w-auto">
          <Tabs 
            tabs={tabItems}
            defaultTab={filter}
            onChange={setFilter}
          />
        </div>
        <div className="text-xs font-mono text-neutral-400 flex items-center gap-2 px-4 py-2 rounded-xl bg-neutral-900/60 border border-neutral-800">
          <Filter className="w-3.5 h-3.5 text-green-400" />
          <span>Showing <strong className="text-white">{filteredItems.length}</strong> decisions</span>
        </div>
      </div>

      {/* Content Rendering */}
      {isLoading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {[1, 2, 3, 4].map(i => (
            <div key={i} className="bg-[#0c0c0e] border border-neutral-800 rounded-2xl p-6 shadow-xl">
              <Skeleton variant="card" className="h-48 bg-neutral-900/50 rounded-xl" />
            </div>
          ))}
        </div>
      ) : isError ? (
        <div className="p-12 text-center bg-[#0c0c0e] border border-red-500/30 rounded-2xl">
          <p className="text-xs font-mono text-red-400 mb-4">Failed to load AI decision logs from server.</p>
          <button 
            type="button"
            onClick={() => refetch()}
            className="px-4 py-2 rounded-xl bg-neutral-900 hover:bg-neutral-800 border border-neutral-700 text-white text-xs font-mono cursor-pointer"
          >
            Retry Connection
          </button>
        </div>
      ) : filteredItems.length === 0 ? (
        <EmptyState 
          icon={Sparkles}
          title="No AI decisions found" 
          description="There are currently no AI decisions matching the selected filter category in the recovery pipeline."
          actionLabel="Reset Filters"
          onAction={() => setFilter('All')}
        />
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {filteredItems.map((item: RecoveryCase) => (
             <AIDecisionCard key={item.id} data={item as any} />
          ))}
        </div>
      )}
    </div>
  );
};